### PR TITLE
Fix include order of traits which reports depends upon

### PR DESCRIPTION
**Pull request by coatless**
While preparing the new CRAN release, my local compile on macOS 10.15.7 yielded an error when compiling of:

```bash
error: no template named 'HasStepSizeSignature' in namespace 'ens::traits';
 did you mean 'HasBatchSizeSignature'?
```

I've verified that the definition is present in `traits`. 

Oddly enough, the new version is passing cleanly with CI checks: coatless/rcppensmallen#39 

I think the error is being triggered because of an include-order issue. Specifically, `ensmallen/include/ensmallen.hpp` needs to have `#include "ensmallen_bits/function.hpp"` placed before `#include "ensmallen_bits/callbacks/report.hpp"`

<details>
<summary>
Full stack trace
</summary>

```bash
clang++ -mmacosx-version-min=10.13 -std=gnu++11 -I"/Library/Frameworks/R.framework/Resources/include" -DNDEBUG  -I'/Library/Frameworks/R.framework/Versions/4.0/Resources/library/Rcpp/include' -I'/Library/Frameworks/R.framework/Versions/4.0/Resources/library/RcppArmadillo/include' -I/usr/local/include  -I../inst/include  -fPIC  -Wall -g -O2  -c RcppExports.cpp -o RcppExports.o
In file included from RcppExports.cpp:4:
In file included from ./../inst/include/RcppEnsmallen.h:25:
In file included from ../inst/include/ensmallen.hpp:74:
../inst/include/ensmallen_bits/callbacks/report.hpp:528:35: error: no template named 'HasStepSizeSignature' in namespace 'ens::traits'; did you mean 'HasBatchSizeSignature'?
  typename std::enable_if<traits::HasStepSizeSignature<OptimizerType>::value,
                          ~~~~~~~~^~~~~~~~~~~~~~~~~~~~
                                  HasBatchSizeSignature
/usr/local/include/ensmallen_bits/function/traits.hpp:381:8: note: 'HasBatchSizeSignature' declared here
struct HasBatchSizeSignature
       ^
In file included from RcppExports.cpp:4:
In file included from ./../inst/include/RcppEnsmallen.h:25:
In file included from ../inst/include/ensmallen.hpp:74:
../inst/include/ensmallen_bits/callbacks/report.hpp:536:36: error: no template named 'HasStepSizeSignature' in namespace 'ens::traits'; did you mean 'HasBatchSizeSignature'?
  typename std::enable_if<!traits::HasStepSizeSignature<OptimizerType>::value,
                           ~~~~~~~~^~~~~~~~~~~~~~~~~~~~
                                   HasBatchSizeSignature
/usr/local/include/ensmallen_bits/function/traits.hpp:381:8: note: 'HasBatchSizeSignature' declared here
struct HasBatchSizeSignature
```

</details>

### CODE REVIEW

File: include/ensmallen.hpp [hunk 1]
```diff
@@ -66,6 +66,9 @@
 #include "ensmallen_bits/utility/any.hpp"
 #include "ensmallen_bits/utility/arma_traits.hpp"
 
+// contains traits, must be placed before report callback
```
Comment (zoq) [inline include/ensmallen.hpp:69]:
```suggestion
// Contains traits, must be placed before report callback.
```

**Review by zoq — APPROVED** [review]
Thanks for the quick patch, let's merge this in as soon as possible and to another release.

**Review by Yashwants19 — APPROVED** [review]
@coatless Thank you for the patch. Lets merge this with the required approval. 👍
